### ISSUE TITLE
Create user service

### ISSUE THREAD

**Issue by marcus-goncalves** [marcus-goncalves/app-events#1]
## **Tasks:**
- [x] Create an user
- [x] Update an user
- [x] Delete an user
- [x] Get an user by email
- [x] Get all user

### **User Description:**
- id
- name
- email
- password
- id_role (FG)
- id_work_shift (FG)
- id_schedule (FG)
- id_teams_group
- is_active
- created_at
- updated_at
- deleted_at

**Comment by marcus-goncalves** [comment]
- Done with routes
- Done with users route objects
