### ISSUE TITLE
Create teams group CRUD

### ISSUE THREAD

**Issue by marcus-goncalves** [marcus-goncalves/app-events#11]
## **Tasks:**
- [x] Create a teams group
- [x] Delete a teams group
- [x] Get all teams groups

### **Schedule Description:**
- id
- key (sanitized description - unique)
- description
- created_at
- updated_at
