### ISSUE TITLE
Create work shift CRUD

### ISSUE THREAD

**Issue by marcus-goncalves** [marcus-goncalves/app-events#6]
## **Tasks:**
- [x] Create an work shift
- [x] Delete an work shift
- [x] Get all work shifts

### **Work shift Description:**
- id
- key (sanitized description - unique)
- description
- created_at
- updated_at
- deleted_at
